flags:
  server:
    library-only: false
    dev: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- friday-0.2.2.0
- friday-juicypixels-0.1.1
- ratio-int-0.1.2
- spool-0.1
resolver: nightly-2015-12-24
